name:                stemlaur.com
title:               stemlaur.com
lang:                fr
url:                 https://www.stemlaur.com
baseurl:             ""
author:
  name:              Laurent Stemmer
  email:             admin@stemlaur.com
timezone:            Europe/Paris
highlighter:         rouge
markdown:            kramdown
permalink:           pretty
paginate:            10
paginate_path:       /blog/:num
excerpt_separator: <!--more-->
exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

twitter:
  username: stemlaur
  card: summary

logo: /assets/images/stemlaur_main.png

social:
  name: Laurent Stemmer
  links:
    - https://twitter.com/stemlaur
    - https://www.linkedin.com/in/stemlaur
    - https://github.com/stemlaur
    - https://keybase.io/stemlaur

sass:
  sass_dir:          _sass
  style:             :compressed

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  title: stemlaur.com
  subtitle: Nouvelles et contes
  path: rss.xml
  excerpt_only: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/stemlaur_main.png
    tagline: stemlaur.com
    description: stemlaur.com
